### ISSUE TITLE
Add support for printing to standard output

### ISSUE THREAD

**Issue by patrickdappollonio** [patrickdappollonio/kubectl-slice#16]
Another feature heard in social media is adding the ability to print the resources to standard output, rather than saving them to files. 

While this idea is not in the core of `kubectl-slice`, it still maintains the idea that you can slice off certain YAML files. For example, one use case scenario could be printing only `Deployments` from an original YAML file, effectively slicing the rest. Something along these lines:

```bash
kubectl-slice -f input.yaml --include-kind Deployment --stdout
```

Assuming, of course, `--stdout` is the flag used to print to standard output.

This could allow neat things such as piping it to `kubectl apply`:

```bash
kubectl-slice -f input.yaml --include-kind Deployment --stdout | kubectl apply -f -
```

Or other actions that behave by piping the output to other programs.

The following questions remain:

**One.** How do we deal with the fact a filename template could've been passed? The following solutions come to my mind:

* We fail running the program if someone provides a template **and** `--stdout` is set at the same time; or
* We still print it, but, like Helm, we add an extra line at the beginning of the file with the name of the generated template name

**Two.** We would have to modify the binary behaviour from their original one where the logs for splitting files are printed to `stdout` and now print them to `stderr`, to make the binary pipe-friendly.

Opening the discussion to any potential user of this feature.

**Comment by georgettica** [comment]
I went here and thought I was a nice feature (unsurprising as the community said that aswell.

The reasoning I see for this is to not save files on disk and still enjoy some features the tool gives:
- remove bad yaml segments
- filtering based on item type

Thus and adding of extra lines might be useful for the splitting, but not for the end user

I hope this input helps :)

I see myself using it to reduce files saved on my machine to test a yaml I obtained :)
