### ISSUE TITLE
Output order of printed files should be preserved

### ISSUE THREAD

**Issue by patrickdappollonio** [patrickdappollonio/kubectl-slice#18]
### What did you do?

Run the command from the README multiple times.

### What did you expect to see?

```
$ kubectl-slice --input-file=example.yaml
Wrote pod-nginx-ingress.yaml -- 57 bytes.
Wrote namespace-production.yaml -- 60 bytes.
2 files generated.
```

... this being always the same output.

### What did you see instead?

Depending on each call, the lines starting with `Wrote` will be mixed:

```
$ kubectl-slice --input-file=example.yaml
Wrote pod-nginx-ingress.yaml -- 57 bytes.
Wrote namespace-production.yaml -- 60 bytes.
2 files generated.
```

```
$ kubectl-slice --input-file=example.yaml
Wrote namespace-production.yaml -- 60 bytes.
Wrote pod-nginx-ingress.yaml -- 57 bytes.
2 files generated.
```

The order of the files should always be the same for the same input. I should sort these files before saving them. 

The issue comes from using a `map` to store these. We could also use a Slice which will preserve the order.

**Comment by georgettica** [comment]
I would even say that the correct sort order can be used by https://github.com/superbrothers/ksort
But that's just me :)

**Comment by patrickdappollonio** [comment]
Hey @georgettica! Appreciate the feedback 😁

I was thinking about a few options:

* Preserve the order they were found -- this might bring the issue though that if the original order changes, then the order here will change as well; or
* Sort by rendered name, descending order; or
* We could sort by kind like you were mentioning 

I like the idea of sorting by kind but some of the files might not be YAML, or they might be, just commented out, for example. 

There's a flag that I added on #4 to skip non Kubernetes resources, and at that point, ksort would work.

Another option could be ksort-then-alphabetically by rendered name.

What do you think?

**Comment by georgettica** [comment]
I think that preserving the original order is best, let the other tool do its job for default behavior

You can also add the 
--sort-with 'none|alphanumeric|ksort'
And make sure that if ksort is selected theand there are items that are not k8s it will work; or
Make sure ksort handles bad inputs

**Comment by patrickdappollonio** [comment]
Oh, that would be great! If `ksort` is enabled we can put the non Kubernetes items last.

I'll put together something. Appreciate the feedback and thanks for letting me know about `ksort`!

**Comment by georgettica** [comment]
Sure!
If I canadd something to the community why not ❤️

**Comment by patrickdappollonio** [comment]
Great thinking! 😋

If you would want to cast your opinion in the other issues marked as [`#help-wanted`](https://github.com/patrickdappollonio/kubectl-slice/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) that would be awesome too!

**Comment by patrickdappollonio** [comment]
I learned today that `ksort` is actually Helm's sorting algorithm based on "installation order". To avoid long flags, I'm thinking:

* `--sort-by-install` which will sort using `ksort`, Helm's own install order (I was thinking about `--sort-by-install-order` but that seems still long)
* `--sort-alphabetically` which will sort alphabetically
* And by default, as they were found

Any thoughts/comments would be greatly appreciated!

**Comment by georgettica** [comment]
Didn't know helm adopted this!
Nice find

These flags seems tab conpleltable and fairly distinct so on the surface that looks ok

**Comment by patrickdappollonio** [comment]
I think it was backwards: `ksort` uses the Helm package from (the now defunct) Tiller. It was moved into the core shortly after. `ksort`'s source code shows it's importing it for quite some time. It's a nifty CLI for the same purpose as Helm's core feature from Tiller.

**Comment by georgettica** [comment]
I would as notes before set the default to not sorting at all, as some have there own tooling in place.

Though I would also accept --sort-disabled to be an option

**Comment by patrickdappollonio** [comment]
Understood, my thinking though is that right now there isn't any sorting at all, which I consider it to be a "bug". The default, if you don't specify anything, will be to sort it with the same order it comes in, rather than randomizing the files as it is right now.

Then, if you want a custom sorting, it'll either be `--sort-by-install` or `-sort-alphabetically`
