### ISSUE TITLE
kubectl-slice does not slice file which uses Windows style line endings

### ISSUE THREAD

**Issue by hollowdrutt** [patrickdappollonio/kubectl-slice#35]
### What did you do?
* Ran the command ```helm template .``` in PowerShell terminal in VS Code on Windows
* Copied the output to Notepad++
* Saved the text to ```complete.yaml```
* Ran the command ```kubectl-slice.exe -f complete.yaml -o .```

### What did you expect to see?

Multiple files generated

### What did you see instead?

One file generated

When pasting the output into Notepad++ and saving to file the line endings got normalized to ```<CR><LF>``` causing kubectl-slice.exe to miss the lines with ```---<CR><LF>```

https://github.com/patrickdappollonio/kubectl-slice/blob/d36ccf84c563e1e15d28032660075c7b30b4ebdc/slice/execute.go#L132

**Comment by patrickdappollonio** [comment]
Apologies for the PR auto-close. It should be fixed now, I included a test to check this as well from a buffer perspective, which should play neatly. If you could try out the new version 1.2.1 that would be awesome!

Let me know!

**Comment by hollowdrutt** [comment]
@patrickdappollonio I have tested with 1.2.1, now it works perfectly, thanks for your quick response and fix!
